### PR TITLE
Frontend Improvements

### PR DESCRIPTION
**Pull request by CaoimheCahill**
Improved frontend for current implementation. 
May need fixes further down the line

image

image

image

### CODE REVIEW

**Comment by kevin-collinss** [comment]
One small change I should've said. Would you be able to add to the fetch notes section that you can specify the note id:
image
The APIs are all in place. I just didn't add it to frontend cause I only threw that frontend together for testing

**Comment by CaoimheCahill** [comment]
> One small change I should've said. Would you be able to add to the fetch notes section that you can specify the note id: image The APIs are all in place. I just didn't add it to frontend cause I only threw that frontend together for testing

Fixed. Added note id text box for adding a review/block aswell. Updated images in description so you can see

**Review by kevin-collinss — APPROVED** [review]
Brilliant, thanks.

**Review by olanhealy — APPROVED** [review]
Approving, looks very nice

**Pull request merged**
